# -*- coding: utf-8 -*-
"""Z SCORE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17nT0Kw4chTPAtxPrX_eqArI_jitr56RD
"""

import numpy as np
import pandas as pd
import scipy.stats as stats



"""array of values"""

data = np.array([6, 7, 7, 13, 13, 15, 16, 19, 22 ])



"""calculate the z-score for each values of arrays"""

stats.zscore(data)

